# Generated by Django 3.0.7 on 2020-08-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resttab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.IntegerField(null=True)),
                ('rname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablebooking.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='booktable',
            name='tables',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablebooking.Resttab'),
        ),
    ]
