# Generated by Django 3.0.7 on 2020-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0002_auto_20200825_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='booktable',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=100, null=True),
        ),
    ]
