# Generated by Django 3.0.7 on 2020-08-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablebooking', '0003_auto_20200825_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablebooking.Restaurant'),
        ),
    ]
